databases:
  - name: trip-planner-db
    plan: free

services:
  - type: web
    name: trip-planner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trip-planner-db
          property: connectionString
